### ISSUE TITLE
The file format is not supported. No ImagePreloader found for null

### ISSUE THREAD

**Issue by kalgon** [hobbut/fop-qrcode-zxing#1]
Hi,

while testing your sample.xml with fop-qrcode-zxing, the qrcode is not drawn in the pdf document and I got the following error:

SEVERE: Image not available. URI: (instream-object). Reason: org.apache.xmlgraphics.image.loader.ImageException: The file format is not supported. No ImagePreloader found for null (No context info available)

**Comment by mpdude** [comment]
This has been quite a while – but can you still remember how you fixed this?
